CREATE TABLE ADMIN.DIM_CUSTOMER 
    ( 
     CUSTOMERKEY NUMBER GENERATED ALWAYS AS IDENTITY 
        ( START WITH 1 CACHE 20 ) , 
     CUSTID      NUMBER , 
     NAME        VARCHAR2 (20) , 
     BIRTHDAY    DATE , 
     ADDRESS     VARCHAR2 (20) , 
     CITY        VARCHAR2 (20) , 
     STATE       VARCHAR2 (20) , 
     ZIP         VARCHAR2 (20) , 
     ISCURRENT   VARCHAR2 (20) , 
     SCD_START   DATE , 
     SCD_END     DATE 
    ) 
    TABLESPACE DATA 
    LOGGING 
;


CREATE UNIQUE INDEX ADMIN.DIM_CUSTOMER_PK ON ADMIN.DIM_CUSTOMER 
    ( 
     CUSTOMERKEY ASC 
    ) 
    TABLESPACE DATA 
    LOGGING 
;

ALTER TABLE ADMIN.DIM_CUSTOMER 
    ADD CONSTRAINT DIM_CUSTOMER_PK PRIMARY KEY ( CUSTOMERKEY ) 
    USING INDEX ADMIN.DIM_CUSTOMER_PK ;