CREATE TABLE ADMIN.DIM_PRODUCT 
    ( 
     PRODUCTKEY  NUMBER GENERATED ALWAYS AS IDENTITY 
        ( START WITH 1 CACHE 20 ) , 
     PRODUCTNAME VARCHAR2 (50) , 
     CATEGORY    VARCHAR2 (20) , 
     SUBCATEGORY VARCHAR2 (20) , 
     BRAND       VARCHAR2 (20) , 
     ISCURRENT   VARCHAR2 (20) , 
     PRODUCTID   NUMBER , 
     SCD_START   DATE , 
     SCD_END     DATE 
    ) 
    TABLESPACE DATA 
    LOGGING 
;


CREATE UNIQUE INDEX ADMIN.DIM_PRODUCT_PK ON ADMIN.DIM_PRODUCT 
    ( 
     PRODUCTKEY ASC 
    ) 
    TABLESPACE DATA 
    LOGGING 
;

ALTER TABLE ADMIN.DIM_PRODUCT 
    ADD CONSTRAINT DIM_PRODUCT_PK PRIMARY KEY ( PRODUCTKEY ) 
    USING INDEX ADMIN.DIM_PRODUCT_PK ;
