CREATE TABLE ADMIN.FACT_SALES 
    ( 
     SALESKEY      NUMBER GENERATED ALWAYS AS IDENTITY 
        ( START WITH 1 CACHE 20 ) , 
     CUSTOMERKEY   NUMBER , 
     PRODUCTKEY    NUMBER , 
     DATEKEY       NUMBER , 
     INVOICENUMBER NUMBER , 
     SALEPRICE     NUMBER , 
     QUANTITY      NUMBER 
    ) 
    TABLESPACE DATA 
    LOGGING 
;


CREATE UNIQUE INDEX ADMIN.FACT_SALES_PK ON ADMIN.FACT_SALES 
    ( 
     SALESKEY ASC 
    ) 
    TABLESPACE DATA 
    LOGGING 
;

ALTER TABLE ADMIN.FACT_SALES 
    ADD CONSTRAINT FACT_SALES_PK PRIMARY KEY ( SALESKEY ) 
    USING INDEX ADMIN.FACT_SALES_PK ;